### ISSUE TITLE
TableNames

### ISSUE THREAD

**Issue by kiquenet** [ElectNewt/WebPersonal#1]
No sé si mejor preguntar aquí o en tu página o el canal de youtube :-)

La clase la generas manualmente o con algún script para consultar todas las tablas.

` internal class TableNames`

Saludos

**Comment by ElectNewt** [comment]
Pora aqui esta bien, no te preocupes, 😂  la genero manualmente.

El motivo de que la parte de "data" contenga el sql como tal es porque explique dapper en un vídeo pasado, y para dapper debes especificar todo a mano.
si no utilizara dappper utilizaria entity framework que lo probé hace unas semanas (despues de no haberlo utilizado en 5 años) y la verdad que ha mejorado un montón.  y ahi no tienes que indicar el nombre únicamente ` DbSet<T> nombreTabla`

Un saludo.
